# Generated by Django 2.0.5 on 2018-06-04 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backpack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='backpack',
            name='trips',
        ),
        migrations.AddField(
            model_name='trip',
            name='backpacks',
            field=models.ManyToManyField(blank=True, to='backpack.Backpack'),
        ),
        migrations.AlterField(
            model_name='backpack',
            name='items',
            field=models.ManyToManyField(blank=True, to='backpack.Item'),
        ),
        migrations.AddField(
            model_name='profile',
            name='backpacks',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backpack.Backpack'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trips',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backpack.Trip'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
