# Generated by Django 2.0.5 on 2018-06-04 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0002_auto_20180604_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backpacks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backpack.Backpack'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backpack.Trip'),
        ),
    ]
