# Generated by Django 2.0.5 on 2018-06-05 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0005_remove_trip_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='backpacks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trips',
        ),
        migrations.AddField(
            model_name='backpack',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backpack.Profile'),
        ),
        migrations.AddField(
            model_name='trip',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backpack.Profile'),
        ),
    ]
