# Generated by Django 2.0.5 on 2018-06-06 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0006_auto_20180605_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='backpack',
            name='items',
        ),
        migrations.AddField(
            model_name='packed',
            name='backpack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backpack.Backpack'),
        ),
        migrations.AddField(
            model_name='packed',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backpack.Item'),
        ),
        migrations.AddField(
            model_name='backpack',
            name='packed_items',
            field=models.ManyToManyField(blank=True, through='backpack.Packed', to='backpack.Item'),
        ),
    ]
