# Generated by Django 2.0.5 on 2018-06-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0007_auto_20180606_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='packed',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
