# Generated by Django 2.0.5 on 2018-06-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack', '0008_packed_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packed',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
